'use client';

import { StitchPreviewBadge } from '@/components/common/StitchPreviewBadge';
import type { StitchPreviewData } from '@/lib/stitchPreview';

interface Props {
  preview: StitchPreviewData;
  screenLabel: string;
}

export function StitchGeneratedFrame({ preview, screenLabel }: Props) {
  return (
    <div className="flex flex-1 flex-col gap-4 bg-[#f3f7f2] px-4 py-4">
      <StitchPreviewBadge title={preview.summary} status={preview.status} source={preview.source} />

      <div className="rounded-[28px] border border-emerald-100 bg-white p-4 shadow-sm">
        <div className="flex items-center justify-between gap-3">
          <div>
            <p className="text-[10px] font-black uppercase tracking-[0.18em] text-emerald-700">Generated Screen</p>
            <p className="mt-1 text-lg font-black text-stone-900">{preview.headline || screenLabel}</p>
          </div>
          <div className="text-right text-xs text-stone-500">
            {preview.projectId && <p>project {preview.projectId}</p>}
            {preview.screenId && <p>screen {preview.screenId}</p>}
          </div>
        </div>

        <div className="mt-4 overflow-hidden rounded-[24px] border border-stone-200 bg-white">
          {preview.html ? (
            <iframe
              title={`STITCH generated ${screenLabel}`}
              srcDoc={preview.html}
              sandbox="allow-scripts allow-same-origin"
              className="h-[720px] w-full bg-white"
            />
          ) : preview.screenshotUrl ? (
            <img
              src={preview.screenshotUrl}
              alt={`${screenLabel} screenshot generated by Stitch`}
              className="h-auto w-full"
            />
          ) : (
            <div className="flex h-[420px] items-center justify-center bg-stone-50 text-sm font-semibold text-stone-400">
              STITCHの画面生成結果を取得できませんでした
            </div>
          )}
        </div>
      </div>

      {preview.highlights.length > 0 && (
        <div className="grid gap-2">
          {preview.highlights.map((item) => (
            <div key={item} className="rounded-2xl border border-emerald-100 bg-white px-4 py-3 text-sm text-stone-600 shadow-sm">
              {item}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
